#!/usr/bin/env python
"""Download released SPARC weights from GitHub Releases, verifying checksums.

    python scripts/download_checkpoints.py               # seed 1 of every encoder + heads (~0.8 GB)
    python scripts/download_checkpoints.py --seeds all   # all five seeds of every encoder (~3.5 GB)
    python scripts/download_checkpoints.py seg_head      # just the five-minute demo
    python scripts/download_checkpoints.py sparc_lambda_0p5 --seeds 1,2,3,4,5
    python scripts/download_checkpoints.py sparc_lambda --seeds all   # a whole sweep
    python scripts/download_checkpoints.py --list

Names are config ids (`sparc_lambda_0p5`, `densecl_lambda_1`, `moco`), sweeps
(`sparc_lambda`, `densecl_lambda`, `baselines`) or the two fine-tuned heads
(`seg_head`, `det_head`). Encoders are filtered by --seeds; heads are not.
Seed 1 of every encoder and both heads are on the GitHub Release; seeds 2-5
are published with the Zenodo record (not yet available -- see MODEL_ZOO.md).
Assets land in ./checkpoints/ (or --dest). See MODEL_ZOO.md for what each is.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

RELEASE = "https://github.com/xRIPEIx/SPARC/releases/download/v1.0.0"

#: Generated by the release build; do not edit by hand.
MANIFEST = Path(__file__).with_name("release_assets.json")
HEAD_NAMES = {"segmentation_head": "seg_head", "detection_head": "det_head"}


def load_manifest() -> list[dict]:
    return json.loads(MANIFEST.read_text())


def select(assets: list[dict], names: list[str], seeds: set[int] | None) -> list[dict]:
    """Assets matching any of `names`; encoders additionally restricted to `seeds`."""
    known = {a["config_id"] for a in assets} | {a["sweep"] for a in assets}
    known |= set(HEAD_NAMES.values())
    unknown = [n for n in names if n not in known]
    if unknown:
        raise SystemExit(f"Unknown asset(s) {unknown}; --list shows what exists")
    picked = []
    for a in assets:
        if a["kind"] == "encoder":
            if names and a["config_id"] not in names and a["sweep"] not in names:
                continue
            if seeds is not None and a["seed"] not in seeds:
                continue
        elif names and HEAD_NAMES[a["kind"]] not in names:
            continue
        picked.append(a)
    return picked


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(asset: dict, dest: Path) -> Path:
    filename, expected = asset["file"], asset["sha256"]
    target = dest / filename
    if target.is_file() and sha256(target) == expected:
        print(f"  {filename}: present, checksum OK")
        return target
    url = f"{RELEASE}/{filename}"
    print(f"  {filename}: downloading {url}")
    dest.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".part")
    urllib.request.urlretrieve(url, tmp)
    got = sha256(tmp)
    if got != expected:
        tmp.unlink()
        raise SystemExit(f"Checksum mismatch for {filename}: {got} != {expected}")
    tmp.replace(target)
    return target


def parse_seeds(text: str) -> set[int] | None:
    if text == "all":
        return None
    return {int(s) for s in text.split(",") if s}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "names", nargs="*", help="config ids, sweeps, seg_head, det_head (default: all)"
    )
    ap.add_argument(
        "--seeds", default="1", help="comma-separated pretraining seeds for encoders, or 'all'"
    )
    ap.add_argument("--dest", type=Path, default=Path("checkpoints"))
    ap.add_argument("--list", action="store_true", help="list every released file and exit")
    a = ap.parse_args(argv)
    assets = load_manifest()
    if a.list:
        for x in assets:
            name = x["config_id"] if x["kind"] == "encoder" else HEAD_NAMES[x["kind"]]
            status = "" if x["published"] else "  (not yet published)"
            print(f"{name:20s} seed {x['seed']}  {x['bytes'] / 1e6:6.1f} MB  {x['file']}{status}")
        return 0
    picked = select(assets, a.names, parse_seeds(a.seeds))
    if not picked:
        raise SystemExit("Nothing selected; check names and --seeds")
    pending = [x for x in picked if not x["published"]]
    picked = [x for x in picked if x["published"]]
    if pending:
        seeds = sorted({x["seed"] for x in pending})
        print(f"skipping {len(pending)} file(s), seed(s) {seeds}: not yet published (MODEL_ZOO.md)")
    if not picked:
        return 1
    total = sum(x["bytes"] for x in picked)
    print(f"{len(picked)} file(s), {total / 1e6:.0f} MB -> {a.dest}/")
    for x in picked:
        fetch(x, a.dest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
