#!/usr/bin/env python
"""Download released SPARC weights from GitHub Releases, verifying checksums.

    python scripts/download_checkpoints.py                 # everything
    python scripts/download_checkpoints.py sparc_lambda_0p5 seg_head
    python scripts/download_checkpoints.py --list

Assets land in ./checkpoints/ (or --dest). See MODEL_ZOO.md for what each is.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

RELEASE = "https://github.com/xRIPEIx/SPARC/releases/download/v1.0.0"

#: name -> (filename, sha256). Generated by the release build; do not edit by hand.
ASSETS: dict[str, tuple[str, str]] = {
    # --- SSL-pretrained encoders, ResNet-18, COCO train2017, 100 epochs (~45 MB each) ---
    "sparc_lambda_0p5": (
        "sparc_lambda_0p5_resnet18_coco_ep100.pth",
        "3fd72963009b33e1a2521682daf5f4445b366358375841b6e31758d248732629",
    ),
    "sparc_lambda_0": (
        "sparc_lambda_0_resnet18_coco_ep100.pth",
        "8bfb5a25cca5a2af074fd284c33c2af273b0dcf8c57b91eb33c967d24e097955",
    ),
    "sparc_lambda_1": (
        "sparc_lambda_1_resnet18_coco_ep100.pth",
        "de4509fcd661cf8895b35232676fce75894121d82f48d6fee2644c5711982217",
    ),
    "moco": (
        "moco_resnet18_coco_ep100.pth",
        "df3a290fa3f0089b27a18448cc423cecb7d94e705d9dce9ab6c375a3622da648",
    ),
    "densecl_lambda_0p5": (
        "densecl_lambda_0p5_resnet18_coco_ep100.pth",
        "76dbf98776972dc7628d0744e5c8565dee30f451a477d344d516dbd97e37cd61",
    ),
    # --- fine-tuned VOC2012 models for the reference SPARC encoder (seed 1) ---
    "seg_head": (
        "sparc_lambda_0p5_voc_segmentation_resnet18.pth",
        "19f7b99bf0c3c4202dfbe9b624639d1c81e04076891aecffe4e3d75e3a5ebf90",
    ),
    "det_head": (
        "sparc_lambda_0p5_voc_detection_resnet18.pth",
        "b143a0f3321209d8f79e8c4580bc84d55b4b918db59fba764c951ebf082d4707",
    ),
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(name: str, dest: Path) -> Path:
    filename, expected = ASSETS[name]
    target = dest / filename
    if target.is_file() and sha256(target) == expected:
        print(f"  {filename}: present, checksum OK")
        return target
    url = f"{RELEASE}/{filename}"
    print(f"  {filename}: downloading {url}")
    dest.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".part")
    urllib.request.urlretrieve(url, tmp)
    got = sha256(tmp)
    if got != expected:
        tmp.unlink()
        raise SystemExit(f"Checksum mismatch for {filename}: {got} != {expected}")
    tmp.replace(target)
    return target


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("names", nargs="*", help=f"any of: {', '.join(ASSETS)}")
    ap.add_argument("--dest", type=Path, default=Path("checkpoints"))
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args(argv)
    if a.list:
        for k, (f, _) in ASSETS.items():
            print(f"{k:22s} {f}")
        return 0
    names = a.names or list(ASSETS)
    unknown = [n for n in names if n not in ASSETS]
    if unknown:
        raise SystemExit(f"Unknown asset(s) {unknown}; --list shows what exists")
    for n in names:
        fetch(n, a.dest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
